name: JKube Demo Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, push image and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: ./mvnw -B verify