name: JKube Demo Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, push image and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: ./mvnw -B verify
      - name: Push Image
        run: |
          ./mvnw -B -Pci oc:build oc:push                             \
          -Djkube.docker.push.username=${{ secrets.QUAY_USERNAME }}   \
          -Djkube.docker.push.password=${{ secrets.QUAY_PASSWORD }}
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.SANDBOX_SERVER }}
          openshift_token: ${{ secrets.SANDBOX_TOKEN }}
          namespace: mnurisan-dev
      - name: Deploy to Dev Sandbox
        run: |
          ./mvnw -B -Pci oc:resource oc:apply